// מחולל את test/logical_hash_contract.json — ה-oracle המשותף ל-Dart ול-Kotlin
// עבור hash-לפי-טבלה. הריצו מחדש רק כששינוי בחוזה ה-hash מכוון.
import 'dart:convert';
import 'dart:io';

import 'package:seforim_library_updater/src/models/patch_table_spec.dart';
import 'package:seforim_library_updater/src/services/logical_content_hasher.dart';
import 'package:sqlite3/sqlite3.dart' as sqlite3;

const setupSql = <String>[
  'CREATE TABLE schema_meta (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL)',
  "INSERT INTO schema_meta VALUES ('db_version','7'),('db_schema_version','5')",
  'CREATE TABLE source (id INTEGER PRIMARY KEY, name TEXT)',
  "INSERT INTO source VALUES (2,'ספריא'),(1,'אוצריא')",
  'CREATE TABLE book (id INTEGER PRIMARY KEY, title TEXT NOT NULL, sourceId INTEGER, order_idx REAL, notes TEXT)',
  "INSERT INTO book VALUES (10,'בְּרֵאשִׁית',1,1.5,NULL),(3,'﻿שמות',2,2.0,''),(7,'ויקרא — פירוש \"רש\"\"י\"',1,-3.25,'multi\nline\ttext')",
  'CREATE TABLE line (id INTEGER PRIMARY KEY, bookId INTEGER NOT NULL, lineIndex INTEGER NOT NULL, content TEXT NOT NULL, plainText TEXT)',
  "INSERT INTO line VALUES (1,10,0,'<b>בראשית</b> ברא','בראשית ברא'),(2,10,1,'אלקים','אלקים'),(3,3,0,'ואלה שמות',NULL),(9007199254740993,7,0,'big id','big id')",
  'CREATE TABLE book_author (bookId INTEGER NOT NULL, authorId INTEGER NOT NULL, PRIMARY KEY (bookId, authorId))',
  'INSERT INTO book_author VALUES (10,2),(3,1),(10,1)',
  'CREATE TABLE link (id INTEGER PRIMARY KEY, sourceLineId INTEGER, targetLineId INTEGER, payload BLOB)',
  "INSERT INTO link VALUES (1,1,3,X'00FF1F02'),(2,2,NULL,X''),(3,3,1,NULL)",
  'CREATE TABLE generation (id INTEGER PRIMARY KEY, name TEXT)',
];

void main() {
  final db = sqlite3.sqlite3.openInMemory();
  for (final sql in setupSql) {
    db.execute(sql);
  }
  const hasher = LogicalContentHasher();
  final tableHashes = <String, String>{
    for (final t in kHashTableOrder) t: hasher.compute(db, tableOrder: [t]),
  };
  final whole = hasher.compute(db, tableOrder: kHashTableOrder);
  final fixture = {
    'contractVersion': 1,
    'description':
        'Shared oracle for the per-table logical content hash. tableHashes[t] = '
            'sha256 of exactly the bytes the whole-DB hasher emits for table t '
            '(" table:<t> " prefix, then cols + rows when the table exists). '
            'wholeHash = sha256 of the concatenation of those per-table streams '
            'in hashTableOrder. Generated by tool/gen_logical_hash_fixture.dart '
            '(Dart hasher, byte-verified against the real v14/v15 chain).',
    'schemaVersion': 5,
    'hashTableOrder': kHashTableOrder,
    'setupSql': setupSql,
    'wholeHash': whole,
    'tableHashes': tableHashes,
  };
  final json = const JsonEncoder.withIndent('  ').convert(fixture);
  File('test/logical_hash_contract.json').writeAsStringSync('$json\n');
  db.close();
  stdout.writeln('whole=$whole tables=${tableHashes.length}');
}
